version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: nuno-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nuno-api
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=nuno
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

volumes:
  mongo_data:
